"""rename department

Revision ID: 5ce5e5a48b4b
Revises: 856e60d2e2f8
Create Date: 2024-04-08 02:31:39.843586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ce5e5a48b4b'
down_revision = '856e60d2e2f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
